[supervisord]
nodaemon=true

[program:redis]
command=redis-server --bind 0.0.0.0 --port 6379
autostart=true
autorestart=true
priority=5

[program:api]
command=/app/main
autostart=true
autorestart=true
priority=10
